project: https://github.com/qualcomm/resource-tuner

branches:
  main:
    modes:
      non-blocking:
        headers:
          - resource-tuner/Core/Client/APIs/Include/ResourceTunerAPIs.h
          - resource-tuner/Core/Modula/Common/Include/Common.h
          - resource-tuner/Core/Extensions/Include/Extensions.h
