name: Deploy Doxygen Docs to gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Doxygen Documentation
        run: doxygen docs/Doxyfile

      - name: Deploy to gh-pages branch
        run: |
          ROOT=$(pwd)
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout --orphan gh-pages
          cd docs/html
          touch .nojekyll
          git init
          git add .
          git commit -m "Deploy Doxygen documentation"
          git push -f "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:gh-pages


