name: Build Resource Tuner

on:
  pull_request:

jobs:
  build:
    runs-on: ["self-hosted", "cseperf-stg-u2204-arm64-xlrg-od-ephem"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libyaml-cpp-dev

    - name: Build project
      run: |
        cd Build
        mkdir build
        cd build
        cmake .. -DBUILD_SIGNALS=ON -DBUILD_CLI=ON -DBUILD_TESTS=ON
        cmake --build .

