name: Build URM

on:
  workflow_dispatch:
  pull_request_target: # requiring access to base repo
    types: [opened, synchronize, reopened]
    branches:
      - main
    # paths-ignore: #update if something has to be ignored.

jobs:
  build:
    runs-on:
      group: GHA-CSEPerf-prd-SelfHosted-RG
      labels: [self-hosted, cseperf-prd-u2204-arm64-xlrg-od-ephem]
    env:
      URM_BINS_DIR: urm-bins                     # base dir name
      URM_INSTALL_PREFIX: ./urm-bins/            # used by CMake
      TAR_NAME: urm-bins.tar.gz                  # output tarball name

    steps:
      - uses: actions/checkout@v5
        with:
          repository: qualcomm/urm-image
          token: ${{ secrets.MY_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build URM image (from Git URL) and load locally
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: urm-image:ci
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sync codebase
        uses: qualcomm/userspace-resource-manager/.github/actions/sync@main
        with:
          event_name: ${{ github.event_name }}
          pr_ref: ${{ github.event.pull_request.head.ref }}
          pr_repo: ${{ github.event.pull_request.head.repo.full_name }}
          base_ref: ${{ github.ref_name }}

      - name: Build userspace-resource-manager in the URM container
        run: |
          docker run --rm -v "$PWD":/workspace -w /workspace urm-image:ci bash -lc '
            set -euo pipefail
            mkdir -p build
            cd build
            cmake .. -DBUILD_TESTS=ON -DBUILD_CLASSIFIER=ON -DCMAKE_INSTALL_PREFIX="${URM_INSTALL_PREFIX}"
            cmake --build .
            make install
          '
      - name: Create a tar file of build
        run: |
          cd build
          tar -cjf "${{ github.workspace }}/${{ env.TAR_NAME }}" "${{ env.URM_BINS_DIR }}"
          cd "${{ github.workspace }}"
          touch file_list.txt
          echo "${{ github.workspace }}/${{ env.TAR_NAME }}" >> file_list.txt

      - name: Upload artifacts to S3
        uses: qualcomm/userspace-resource-manager/.github/actions/aws_s3_helper@main
        with:
          s3_bucket: qli-prd-cseperf-gh-artifacts
          mode: multi-upload
          local_file: file_list.txt
